---
settings:
  parallel: true

driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
#  - name: ubuntu-12.04
#    driver_config:
#      box: opscode-ubuntu-12.04
#      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
#    run_list:
#      - recipe[rackspace_apt::default]
#    attributes:
#      rackspace_apt:
#        switch:
#          delete_sources_list: true
#  - name: debian-7.2
#    driver_config:
#      box: opscode-debian-7.2.0
#      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
#    run_list:
#      - recipe[rackspace_apt::default]
#    attributes:
#      rackspace_apt:
#        switch:
#          delete_sources_list: true
  - name: centos-6.4
    driver_config:
      box: opscode-centos-6.4
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.4_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[rackspace_jboss::default]

  - name: jboss_7.0.0
    run_list:
      - recipe[rackspace_jboss::default]
    attributes:
      rackspace_jboss:
        jboss_version: "7.0.0"

  - name: set_some_overrides
    run_list:
      - recipe[rackspace_jboss::default]
    attributes:
      rackspace_jboss:
        jdk_flavor: "openjdk"
        jdk_version: "6"
        config:
          management_listen_address: "127.0.0.1"
          mgmt-users:
            admin: "2a0923285184943425d1f53ddd58ec7a"
        JAVA_OPTS:
          set:
            xms: "-Xms128m"
            xmx: "-Xmx768m"
        mysql_jdbc:
          enabled: true
          version: '5.1.25'
